Version 4
SymbolType BLOCK
RECTANGLE Normal 64 0 -96 -64
SYMATTR Prefix x
SYMATTR Value INA240A3
PIN 48 -64 BOTTOM 8
PINATTR PinName out
PINATTR SpiceOrder 1
PIN 48 0 TOP 8
PINATTR PinName INP
PINATTR SpiceOrder 2
PIN 64 -32 LEFT 8
PINATTR PinName INN
PINATTR SpiceOrder 3
PIN -16 0 TOP 8
PINATTR PinName Ref1
PINATTR SpiceOrder 4
PIN -80 -64 BOTTOM 8
PINATTR PinName Ref2
PINATTR SpiceOrder 5
PIN -96 -32 RIGHT 8
PINATTR PinName vcc
PINATTR SpiceOrder 6
PIN -80 0 TOP 8
PINATTR PinName gnd
PINATTR SpiceOrder 7
